server:
  port: 2333

lavalink:
  server:
    password: "hurain"
    sources:
      youtube: true
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      http: true
    bufferDurationMs: 400
    frameBufferDurationMs: 2000
    opusEncodingQuality: 10
    resamplingQuality: HIGH

logging:
  file:
    enable: false
  level:
    root: INFO
